### ISSUE TITLE
Issues with flex-flow: row wrap, items are cascaded

### ISSUE THREAD

**Issue by jonas-meyer** [schnerring/hugo-mod-json-resume#3]
Thanks for the module, very helpful to set up my personal website. I'm using the hugo-coder theme with this module and the following custom css: 

```css
.jr__item-meta {
  align-items: center;
  flex-flow: row wrap;
}

.jr__date,
.jr__date-range,
.jr-work__location {
  flex-grow: 1;
  text-align: right;
}
```

I'm getting the following output:
<img width="828" alt="Screenshot 2023-03-17 at 17 17 25" src="https://user-images.githubusercontent.com/19151471/225974153-2d3cc6ed-89df-4226-adbd-9f8e7cf046e4.png">

According to the README.md, the items in item-meta should align properly, is this something that you would know the solution to? Otherwise I'll need to read up on some css!
